"use client";

import { FormEvent, useState } from "react";
import type { ExperienceItem, InternalApp, MediaAsset, SiteSections } from "@/types/cms";

const newId = (prefix: string) => `${prefix}-${Date.now().toString(36)}`;

export function ContentEditor({ initial, media, reload }: { initial: SiteSections; media: MediaAsset[]; reload: () => Promise<void> }) {
  const [content, setContent] = useState(initial); const [message, setMessage] = useState("");
  const images = media.filter((item) => item.mime_type.startsWith("image/")); const pdfs = media.filter((item) => item.mime_type === "application/pdf");
  function update<K extends keyof SiteSections>(key: K, value: SiteSections[K]) { setContent((current) => ({ ...current, [key]: value })); }
  async function save(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/content", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(content) }); const result = await response.json(); setMessage(response.ok ? "Website content saved as a private draft." : result.error); if (response.ok) await reload(); }
  function addExperience() { const item: ExperienceItem = { id: newId("experience"), period: "", location: "", title: "", company: "", summary: "" }; update("experience", { ...content.experience, items: [...content.experience.items, item] }); }
  function addApp() { const item: InternalApp = { id: newId("tool"), name: "", purpose: "", problem: "", contribution: "", technologies: [], url: "https://", featured: false }; update("innovation", { ...content.innovation, apps: [...content.innovation.apps, item] }); }
  return <section className="admin-panel"><p className="admin-kicker">Structured fields</p><h1>Website content</h1><p className="admin-lead">Edit copy and section settings safely. Content is plain text and sanitized—there is no unrestricted HTML page builder.</p><form className="content-form" onSubmit={save}>
    <details open><summary>Navigation & section visibility</summary><div className="editor-block"><h2>Navigation labels</h2>{content.navigation.items.map((item, index) => <div className="repeat-row" key={item.id}><label>Label<input value={item.label} onChange={(event) => { const items = [...content.navigation.items]; items[index] = { ...item, label: event.target.value }; update("navigation", { ...content.navigation, items }); }} /></label><label className="check-field"><input type="checkbox" checked={item.visible} onChange={(event) => { const items = [...content.navigation.items]; items[index] = { ...item, visible: event.target.checked }; update("navigation", { ...content.navigation, items }); }} /> Show in navigation</label></div>)}<label>Header resume label<input value={content.navigation.resumeLabel} onChange={(event) => update("navigation", { ...content.navigation, resumeLabel: event.target.value })} /></label><h2>Public sections</h2><div className="check-grid">{Object.entries(content.visibility).map(([key, visible]) => <label className="check-field" key={key}><input type="checkbox" checked={visible} onChange={(event) => update("visibility", { ...content.visibility, [key]: event.target.checked })} /> {key.replace(/^./, (letter) => letter.toUpperCase())}</label>)}</div></div></details>
    <details open><summary>Hero & profile</summary><div className="editor-block field-grid"><Text label="Hero eyebrow" value={content.hero.eyebrow} onChange={(value) => update("hero", { ...content.hero, eyebrow: value })} /><Text label="Hero title" value={content.hero.title} onChange={(value) => update("hero", { ...content.hero, title: value })} /><Text label="Positioning line" value={content.hero.positioning} onChange={(value) => update("hero", { ...content.hero, positioning: value })} /><Text label="Location" value={content.hero.location} onChange={(value) => update("hero", { ...content.hero, location: value })} /><Area label="Introduction" value={content.hero.introduction} onChange={(value) => update("hero", { ...content.hero, introduction: value })} /><label>Profile photograph<select value={content.hero.profileMediaId ?? ""} onChange={(event) => update("hero", { ...content.hero, profileMediaId: event.target.value ? Number(event.target.value) : null })}><option value="">Verified resume portrait fallback</option>{images.map((item) => <option key={item.id} value={item.id}>{item.file_name}</option>)}</select></label><Text label="Primary button label" value={content.hero.primaryButtonLabel} onChange={(value) => update("hero", { ...content.hero, primaryButtonLabel: value })} /><Text label="Resume button label" value={content.hero.resumeButtonLabel} onChange={(value) => update("hero", { ...content.hero, resumeButtonLabel: value })} /><Text label="Profile heading" value={content.profile.heading} onChange={(value) => update("profile", { ...content.profile, heading: value })} /><Area label="Profile lead" value={content.profile.lead} onChange={(value) => update("profile", { ...content.profile, lead: value })} /><Area label="Profile paragraphs — one per line" value={content.profile.paragraphs.join("\n")} onChange={(value) => update("profile", { ...content.profile, paragraphs: value.split("\n").filter(Boolean) })} /><Text label="Profile pillars — comma separated" value={content.profile.pillars.join(", ")} onChange={(value) => update("profile", { ...content.profile, pillars: value.split(",").map((item) => item.trim()).filter(Boolean) })} /></div></details>
    <details><summary>Experience</summary><div className="editor-block"><Text label="Section heading" value={content.experience.heading} onChange={(value) => update("experience", { ...content.experience, heading: value })} />{content.experience.items.map((item, index) => <div className="repeat-card" key={item.id}><div className="field-grid"><Text label="Period" value={item.period} onChange={(value) => editExperience(index, { period: value })} /><Text label="Location" value={item.location} onChange={(value) => editExperience(index, { location: value })} /><Text label="Title" value={item.title} onChange={(value) => editExperience(index, { title: value })} /><Text label="Company" value={item.company} onChange={(value) => editExperience(index, { company: value })} /></div><Area label="Achievement-focused summary" value={item.summary} onChange={(value) => editExperience(index, { summary: value })} /><button type="button" className="danger-link" onClick={() => update("experience", { ...content.experience, items: content.experience.items.filter((_, row) => row !== index) })}>Remove role</button></div>)}<button type="button" className="admin-secondary" onClick={addExperience}>Add experience</button></div></details>
    <details><summary>Portfolio & capabilities</summary><div className="editor-block field-grid"><Text label="Portfolio heading" value={content.portfolio.heading} onChange={(value) => update("portfolio", { ...content.portfolio, heading: value })} /><Area label="Portfolio introduction" value={content.portfolio.introduction} onChange={(value) => update("portfolio", { ...content.portfolio, introduction: value })} /><Area label="No-image message" value={content.portfolio.emptyMessage} onChange={(value) => update("portfolio", { ...content.portfolio, emptyMessage: value })} /><Text label="Capabilities heading" value={content.capabilities.heading} onChange={(value) => update("capabilities", { ...content.capabilities, heading: value })} /><Area label="Tools — one per line" value={content.capabilities.tools.join("\n")} onChange={(value) => update("capabilities", { ...content.capabilities, tools: value.split("\n").filter(Boolean) })} /></div><div className="editor-block"><h2>Capability groups</h2>{content.capabilities.items.map((item, index) => <div className="repeat-row" key={item.id}><Text label="Title" value={item.title} onChange={(value) => { const items = [...content.capabilities.items]; items[index] = { ...item, title: value }; update("capabilities", { ...content.capabilities, items }); }} /><Text label="Summary" value={item.summary} onChange={(value) => { const items = [...content.capabilities.items]; items[index] = { ...item, summary: value }; update("capabilities", { ...content.capabilities, items }); }} /></div>)}</div></details>
    <details><summary>AI & Creative Innovation</summary><div className="editor-block"><Text label="Section heading" value={content.innovation.heading} onChange={(value) => update("innovation", { ...content.innovation, heading: value })} /><Area label="Introduction" value={content.innovation.introduction} onChange={(value) => update("innovation", { ...content.innovation, introduction: value })} /><Area label="Private-access note" value={content.innovation.accessNote} onChange={(value) => update("innovation", { ...content.innovation, accessNote: value })} />{content.innovation.apps.map((app, index) => <div className="repeat-card" key={app.id}><div className="field-grid"><Text label="Application name" value={app.name} onChange={(value) => editApp(index, { name: value })} /><Text label="HTTPS link" value={app.url} onChange={(value) => editApp(index, { url: value })} /></div><Area label="Purpose" value={app.purpose} onChange={(value) => editApp(index, { purpose: value })} /><Area label="Problem solved" value={app.problem} onChange={(value) => editApp(index, { problem: value })} /><Area label="Verified contribution" value={app.contribution} onChange={(value) => editApp(index, { contribution: value })} /><Text label="Technologies — comma separated" value={app.technologies.join(", ")} onChange={(value) => editApp(index, { technologies: value.split(",").map((item) => item.trim()).filter(Boolean) })} /><label className="check-field"><input type="checkbox" checked={app.featured} onChange={(event) => editApp(index, { featured: event.target.checked })} /> Feature among first four</label><button type="button" className="danger-link" onClick={() => update("innovation", { ...content.innovation, apps: content.innovation.apps.filter((_, row) => row !== index) })}>Remove application</button></div>)}<button type="button" className="admin-secondary" onClick={addApp}>Add internal application</button></div></details>
    <details><summary>Education, contact & footer</summary><div className="editor-block field-grid"><Text label="Education heading" value={content.education.heading} onChange={(value) => update("education", { ...content.education, heading: value })} /><Text label="Languages — comma separated" value={content.education.languages.join(", ")} onChange={(value) => update("education", { ...content.education, languages: value.split(",").map((item) => item.trim()).filter(Boolean) })} />{content.education.items.map((item, index) => <div className="repeat-card" key={item.id}><Text label="Qualification" value={item.qualification} onChange={(value) => { const items = [...content.education.items]; items[index] = { ...item, qualification: value }; update("education", { ...content.education, items }); }} /><Text label="Institution" value={item.institution} onChange={(value) => { const items = [...content.education.items]; items[index] = { ...item, institution: value }; update("education", { ...content.education, items }); }} /></div>)}<Text label="Contact heading" value={content.contact.heading} onChange={(value) => update("contact", { ...content.contact, heading: value })} /><Text label="Email" type="email" value={content.contact.email} onChange={(value) => update("contact", { ...content.contact, email: value })} /><Text label="Phone" value={content.contact.phone} onChange={(value) => update("contact", { ...content.contact, phone: value })} /><Text label="Location" value={content.contact.location} onChange={(value) => update("contact", { ...content.contact, location: value })} /><Text label="Contact button" value={content.contact.buttonLabel} onChange={(value) => update("contact", { ...content.contact, buttonLabel: value })} /><label>Resume file<select value={content.resume.mediaId ?? ""} onChange={(event) => update("resume", { ...content.resume, mediaId: event.target.value ? Number(event.target.value) : null })}><option value="">Verified resume PDF fallback</option>{pdfs.map((item) => <option key={item.id} value={item.id}>{item.file_name}</option>)}</select></label><Text label="Resume download label" value={content.resume.downloadLabel} onChange={(value) => update("resume", { ...content.resume, downloadLabel: value })} /><Text label="Footer name" value={content.footer.copyright} onChange={(value) => update("footer", { ...content.footer, copyright: value })} /><Text label="Footer descriptor" value={content.footer.descriptor} onChange={(value) => update("footer", { ...content.footer, descriptor: value })} /></div></details>
    <div className="sticky-save"><button className="admin-primary">Save Content Draft</button>{message && <p role="status">{message}</p>}</div>
  </form></section>;

  function editExperience(index: number, change: Partial<ExperienceItem>) { const items = [...content.experience.items]; items[index] = { ...items[index], ...change }; update("experience", { ...content.experience, items }); }
  function editApp(index: number, change: Partial<InternalApp>) { const apps = [...content.innovation.apps]; apps[index] = { ...apps[index], ...change }; update("innovation", { ...content.innovation, apps }); }
}

function Text({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label>{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Area({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label>{label}<textarea rows={4} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
