"use client";

import { useState } from "react";
import { fontOptions } from "@/content/fonts";
import { themeVariables } from "@/lib/cms/theme";
import type { ThemeSettings } from "@/types/cms";

const fontFields: Array<[keyof ThemeSettings, string]> = [["primaryFont", "Primary font"], ["headingFont", "Heading font"], ["bodyFont", "Body font"]];
const sizeFields: Array<[keyof ThemeSettings, string, number, number]> = [["bodySize", "Base body size", 14, 20], ["heroHeadingSize", "Hero heading max", 52, 132], ["sectionHeadingSize", "Section heading max", 36, 84], ["cardHeadingSize", "Card heading max", 22, 48], ["navSize", "Navigation size", 11, 18], ["buttonSize", "Button size", 11, 18], ["borderRadius", "Border radius", 0, 32], ["sectionSpacing", "Section spacing", 56, 200], ["containerWidth", "Container width", 960, 1600]];
const colorFields: Array<[keyof ThemeSettings, string]> = [["primaryColor", "Primary"], ["secondaryColor", "Secondary"], ["accentColor", "Accent"], ["backgroundColor", "Background"], ["surfaceColor", "Surface / card"], ["headingColor", "Heading text"], ["bodyColor", "Body text"], ["buttonBackground", "Button background"], ["buttonText", "Button text"], ["borderColor", "Borders"]];

export function StyleEditor({ initial, reload, publish }: { initial: ThemeSettings; reload: () => Promise<void>; publish: () => Promise<void> }) {
  const [theme, setTheme] = useState(initial); const [message, setMessage] = useState("");
  function set<K extends keyof ThemeSettings>(key: K, value: ThemeSettings[K]) { setTheme((current) => ({ ...current, [key]: value })); }
  async function save(candidate = theme, action = "save") { const response = await fetch("/api/admin/theme", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(action === "reset" ? { action } : { theme: candidate }) }); const result = await response.json(); if (response.ok) { setTheme(result.theme); setMessage(action === "reset" ? "Default theme restored as a draft." : "Style saved as draft."); await reload(); } else setMessage(result.error); }
  async function reset() { if (confirm("Reset every theme token to the curated default? This remains a draft until you publish.")) await save(theme, "reset"); }
  return <section className="admin-panel"><p className="admin-kicker">Controlled design tokens</p><h1>Website Style</h1><p className="admin-lead">Safe ranges and a curated font list keep changes responsive. Nothing here can restructure the page.</p><div className="style-layout"><form className="style-controls" onSubmit={(event) => { event.preventDefault(); void save(); }}><fieldset><legend>Typography</legend>{fontFields.map(([key, label]) => <label key={key}>{label}<select value={String(theme[key])} onChange={(event) => set(key, event.target.value)}>{fontOptions.map((font) => <option value={font.value} key={font.value}>{font.label}</option>)}</select></label>)}{sizeFields.map(([key, label, min, max]) => <label key={key}>{label}<span className="range-field"><input type="range" min={min} max={max} value={Number(theme[key])} onChange={(event) => set(key, Number(event.target.value))} /><output>{theme[key]} px</output></span></label>)}</fieldset><fieldset><legend>Colour system</legend><div className="color-grid">{colorFields.map(([key, label]) => <label key={key}>{label}<span className="color-field"><input type="color" value={String(theme[key])} onChange={(event) => set(key, event.target.value)} /><input value={String(theme[key])} pattern="#[0-9a-fA-F]{6}" onChange={(event) => set(key, event.target.value)} /></span></label>)}</div></fieldset><div className="form-actions"><button className="admin-primary">Save Draft</button><button type="button" className="admin-secondary" onClick={() => void publish()}>Publish Changes</button><button type="button" className="danger-link" onClick={() => void reset()}>Reset to Default Theme</button></div>{message && <p role="status">{message}</p>}</form><div className="live-preview" style={themeVariables(theme)}><p className="admin-kicker">Live style preview</p><h2>Design with clarity, scale and purpose.</h2><p>Typography, colour, spacing and controls update here before you save the draft.</p><button>Primary action</button><div><article><span>01</span><h3>Brand & campaign</h3><p>A controlled card surface and responsive type scale.</p></article><article><span>02</span><h3>Event environments</h3><p>Tokens stay consistent across every public section.</p></article></div></div></div></section>;
}
