create extension if not exists pgcrypto with schema extensions;

create type public.project_status as enum ('draft', 'published', 'unpublished');

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique check (email = lower(email)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(name) between 1 and 100),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,79}$'),
  position integer not null default 0 check (position between 0 and 10000),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.projects (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,79}$'),
  name text not null check (char_length(name) between 1 and 160),
  client text not null default '' check (char_length(client) <= 160),
  year text not null default '' check (char_length(year) <= 40),
  category_id bigint references public.categories(id) on delete set null,
  overview text not null default '' check (char_length(overview) <= 1600),
  role text not null default '' check (char_length(role) <= 1200),
  contribution text not null default '' check (char_length(contribution) <= 1200),
  deliverables jsonb not null default '[]'::jsonb check (jsonb_typeof(deliverables) = 'array'),
  position integer not null default 0 check (position between 0 and 10000),
  featured boolean not null default false,
  status public.project_status not null default 'draft',
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.media_assets (
  id bigint generated by default as identity primary key,
  file_name text not null check (char_length(file_name) between 1 and 240),
  storage_path text not null unique check (char_length(storage_path) between 1 and 500),
  mime_type text not null check (mime_type in ('image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/svg+xml', 'application/pdf')),
  byte_size bigint not null check (byte_size > 0 and byte_size <= 15728640),
  content_hash text not null unique check (content_hash ~ '^[a-f0-9]{64}$'),
  alt_text text not null default '' check (char_length(alt_text) <= 240),
  width integer check (width is null or width between 1 and 30000),
  height integer check (height is null or height between 1 and 30000),
  variants jsonb not null default '{}'::jsonb check (jsonb_typeof(variants) = 'object'),
  uploaded_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.project_images (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  media_id bigint not null references public.media_assets(id) on delete restrict,
  caption text not null default '' check (char_length(caption) <= 300),
  alt_text text not null check (char_length(alt_text) between 4 and 240),
  position integer not null default 0 check (position between 0 and 10000),
  focal_x numeric(5,2) not null default 50 check (focal_x between 0 and 100),
  focal_y numeric(5,2) not null default 50 check (focal_y between 0 and 100),
  is_cover boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, media_id)
);

create table public.site_content (
  singleton boolean primary key default true check (singleton),
  draft_content jsonb not null check (jsonb_typeof(draft_content) = 'object'),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table public.theme_settings (
  singleton boolean primary key default true check (singleton),
  draft_theme jsonb not null check (jsonb_typeof(draft_theme) = 'object'),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table public.published_site (
  singleton boolean primary key default true check (singleton),
  revision bigint not null default 0 check (revision >= 0),
  snapshot jsonb not null check (jsonb_typeof(snapshot) = 'object'),
  published_by uuid references auth.users(id) on delete set null,
  published_at timestamptz not null default now()
);

create table public.publication_history (
  id bigint generated by default as identity primary key,
  revision bigint not null unique,
  snapshot jsonb not null check (jsonb_typeof(snapshot) = 'object'),
  published_by uuid references auth.users(id) on delete set null,
  published_at timestamptz not null default now()
);

create table public.audit_log (
  id bigint generated always as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  table_name text not null,
  record_id text,
  occurred_at timestamptz not null default now()
);

create index projects_category_id_idx on public.projects(category_id);
create index projects_status_position_idx on public.projects(status, position);
create index project_images_project_position_idx on public.project_images(project_id, position);
create index project_images_media_id_idx on public.project_images(media_id);
create unique index project_images_one_cover_idx on public.project_images(project_id) where is_cover;
create index media_assets_uploaded_by_idx on public.media_assets(uploaded_by);
create index audit_log_actor_occurred_idx on public.audit_log(actor_id, occurred_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_cms_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

create or replace function public.audit_cms_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  row_data jsonb;
begin
  row_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  insert into public.audit_log (actor_id, operation, table_name, record_id)
  values ((select auth.uid()), tg_op, tg_table_name, coalesce(row_data ->> 'id', row_data ->> 'singleton', row_data ->> 'user_id'));
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create or replace function public.publish_site(new_snapshot jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  next_revision bigint;
  published_snapshot jsonb;
begin
  if not (select public.is_cms_admin()) then raise exception 'Not authorized'; end if;
  if jsonb_typeof(new_snapshot) <> 'object' then raise exception 'Invalid snapshot'; end if;
  select revision + 1 into next_revision from public.published_site where singleton for update;
  published_snapshot := jsonb_set(jsonb_set(new_snapshot, '{revision}', to_jsonb(next_revision)), '{publishedAt}', to_jsonb(now()));
  insert into public.publication_history (revision, snapshot, published_by) values (next_revision, published_snapshot, (select auth.uid()));
  update public.published_site set revision = next_revision, snapshot = published_snapshot, published_by = (select auth.uid()), published_at = now() where singleton;
  return published_snapshot;
end;
$$;

create trigger admin_users_updated_at before update on public.admin_users for each row execute function public.set_updated_at();
create trigger categories_updated_at before update on public.categories for each row execute function public.set_updated_at();
create trigger projects_updated_at before update on public.projects for each row execute function public.set_updated_at();
create trigger media_assets_updated_at before update on public.media_assets for each row execute function public.set_updated_at();
create trigger project_images_updated_at before update on public.project_images for each row execute function public.set_updated_at();
create trigger site_content_updated_at before update on public.site_content for each row execute function public.set_updated_at();
create trigger theme_settings_updated_at before update on public.theme_settings for each row execute function public.set_updated_at();

create trigger categories_audit after insert or update or delete on public.categories for each row execute function public.audit_cms_change();
create trigger projects_audit after insert or update or delete on public.projects for each row execute function public.audit_cms_change();
create trigger media_assets_audit after insert or update or delete on public.media_assets for each row execute function public.audit_cms_change();
create trigger project_images_audit after insert or update or delete on public.project_images for each row execute function public.audit_cms_change();
create trigger site_content_audit after insert or update or delete on public.site_content for each row execute function public.audit_cms_change();
create trigger theme_settings_audit after insert or update or delete on public.theme_settings for each row execute function public.audit_cms_change();
create trigger published_site_audit after insert or update or delete on public.published_site for each row execute function public.audit_cms_change();

alter table public.admin_users enable row level security;
alter table public.categories enable row level security;
alter table public.projects enable row level security;
alter table public.media_assets enable row level security;
alter table public.project_images enable row level security;
alter table public.site_content enable row level security;
alter table public.theme_settings enable row level security;
alter table public.published_site enable row level security;
alter table public.publication_history enable row level security;
alter table public.audit_log enable row level security;

create policy admin_users_read_self on public.admin_users for select to authenticated using (user_id = (select auth.uid()));
create policy categories_admin_all on public.categories for all to authenticated using ((select public.is_cms_admin())) with check ((select public.is_cms_admin()));
create policy projects_admin_all on public.projects for all to authenticated using ((select public.is_cms_admin())) with check ((select public.is_cms_admin()));
create policy media_assets_admin_all on public.media_assets for all to authenticated using ((select public.is_cms_admin())) with check ((select public.is_cms_admin()));
create policy project_images_admin_all on public.project_images for all to authenticated using ((select public.is_cms_admin())) with check ((select public.is_cms_admin()));
create policy site_content_admin_all on public.site_content for all to authenticated using ((select public.is_cms_admin())) with check ((select public.is_cms_admin()));
create policy theme_settings_admin_all on public.theme_settings for all to authenticated using ((select public.is_cms_admin())) with check ((select public.is_cms_admin()));
create policy published_site_public_read on public.published_site for select to anon, authenticated using (true);
create policy published_site_admin_write on public.published_site for all to authenticated using ((select public.is_cms_admin())) with check ((select public.is_cms_admin()));
create policy publication_history_admin_all on public.publication_history for all to authenticated using ((select public.is_cms_admin())) with check ((select public.is_cms_admin()));
create policy audit_log_admin_read on public.audit_log for select to authenticated using ((select public.is_cms_admin()));

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke all on function public.is_cms_admin() from public, anon;
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.audit_cms_change() from public, anon, authenticated;
revoke all on function public.publish_site(jsonb) from public, anon;

grant usage on schema public to anon, authenticated;
grant execute on function public.is_cms_admin() to authenticated;
grant execute on function public.publish_site(jsonb) to authenticated;
grant select on public.published_site to anon;
grant select on public.admin_users to authenticated;
grant select, insert, update, delete on public.categories, public.projects, public.media_assets, public.project_images, public.site_content, public.theme_settings, public.published_site, public.publication_history to authenticated;
grant select on public.audit_log to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant all privileges on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.is_cms_admin(), public.publish_site(jsonb) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('cms-media', 'cms-media', false, 15728640, array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/svg+xml', 'application/pdf'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy cms_media_admin_read on storage.objects for select to authenticated using (bucket_id = 'cms-media' and (select public.is_cms_admin()));
create policy cms_media_admin_insert on storage.objects for insert to authenticated with check (bucket_id = 'cms-media' and (storage.foldername(name))[1] = (select auth.uid())::text and (select public.is_cms_admin()));
create policy cms_media_admin_update on storage.objects for update to authenticated using (bucket_id = 'cms-media' and (select public.is_cms_admin())) with check (bucket_id = 'cms-media' and (storage.foldername(name))[1] = (select auth.uid())::text and (select public.is_cms_admin()));
create policy cms_media_admin_delete on storage.objects for delete to authenticated using (bucket_id = 'cms-media' and (select public.is_cms_admin()));

insert into public.categories (name, slug, position) values
  ('Event & Exhibition', 'event-exhibition', 0),
  ('Brand & Campaign', 'brand-campaign', 1),
  ('Digital & Social', 'digital-social', 2),
  ('Presentation', 'presentation', 3),
  ('Print & Editorial', 'print-editorial', 4),
  ('Hospitality', 'hospitality', 5),
  ('Banking & Corporate', 'banking-corporate', 6);

insert into public.projects (slug, name, client, year, category_id, overview, role, contribution, deliverables, position, featured, status)
select 'leap-informa', 'LEAP', 'Informa', '2021–2026', id, 'Selected event-design work supporting the visual presence and on-site experience of LEAP across multiple editions.', 'Senior graphic design and production contribution across a large, fast-moving event programme.', 'Developed and adapted approved visual systems across event touchpoints in collaboration with creative, account and production teams.', '["Event identity rollout", "Main stages and entrances", "Signage and agenda screens", "Speaker and sponsor graphics", "Post-show reports"]'::jsonb, 0, true, 'draft'::public.project_status from public.categories where slug = 'event-exhibition'
union all select 'black-hat-mea', 'Black Hat MEA', 'Informa', '2022', id, 'Selected event and exhibition graphics created for the Black Hat MEA environment.', 'Design and production contribution for large-format event communications.', 'Applied the event visual language across entrances, information surfaces, themed villages and key visitor touchpoints.', '["Entrances", "Agenda walls", "Village signage", "Key-visual adaptations"]'::jsonb, 1, true, 'draft' from public.categories where slug = 'event-exhibition'
union all select 'world-police-summit', 'World Police Summit', 'Informa', '2023', id, 'Key-visual and campaign development for the World Police Summit across web, advertising and social formats.', 'Selected design work from concept development through campaign rollout.', 'Contributed visual routes, stylescape development and production-ready adaptations across approved formats.', '["Key visual", "Stylescape", "Website banners", "Advertising", "Social templates"]'::jsonb, 2, true, 'draft' from public.categories where slug = 'brand-campaign'
union all select 'messe-frankfurt-middle-east', 'Messe Frankfurt Middle East', 'Messe Frankfurt Middle East', '2023–2024', id, 'Multi-show exhibition branding designed to remain consistent while respecting distinct event identities.', 'Senior design and rollout contribution across exhibition brands.', 'Extended approved show identities across coordinated campaign and event deliverables.', '["Exhibition branding", "Campaign adaptations", "Digital assets", "Print production"]'::jsonb, 3, true, 'draft' from public.categories where slug = 'event-exhibition'
union all select 'emaar-address-hotels', 'Emaar / Address Hotels & Resorts', 'Emaar Hospitality Group', '2018–2020', id, 'Hospitality communication across brand collateral, campaigns and digital touchpoints.', 'Selected design and production work for luxury hospitality brands.', 'Produced brand-consistent collateral and campaign adaptations in collaboration with account and creative teams.', '["Brand collateral", "Digital newsletters", "Hotel campaigns", "Social media"]'::jsonb, 4, true, 'draft' from public.categories where slug = 'hospitality'
union all select 'emirates-nbd-wealth-private-banking', 'Emirates NBD — Wealth & Private Banking', 'Emirates NBD', '2023–2024', id, 'Corporate and customer communication for wealth and private-banking audiences.', 'Presentation, editorial and digital design contribution.', 'Structured complex information into clear, brand-aligned presentation and collateral formats.', '["Corporate presentations", "Brochures", "EDMs", "Award carousels", "Branch collateral"]'::jsonb, 5, true, 'draft' from public.categories where slug = 'banking-corporate'
union all select 'emirates-nbd-retail', 'Emirates NBD — Retail Campaigns', 'Emirates NBD', 'Selected work', id, 'Bilingual retail-banking campaign content across social, digital and motion formats.', 'Campaign adaptation, digital design and production contribution.', 'Created consistent asset families across formats while maintaining approved campaign and brand requirements.', '["Bilingual social assets", "Instagram stories", "Carousels", "Animated adaptations"]'::jsonb, 6, true, 'draft' from public.categories where slug = 'digital-social'
union all select 'emirates-islamic-bank', 'Emirates Islamic Bank', 'Emirates Islamic', '2022–2023', id, 'Campaign concepts and customer communication for banking products and security awareness.', 'Selected campaign design and rollout contribution.', 'Developed and adapted campaign communication across digital and customer-facing formats.', '["Campaign concepts", "Salary-transfer communication", "Savings campaigns", "Anti-fraud communication"]'::jsonb, 7, false, 'draft' from public.categories where slug = 'banking-corporate'
union all select 'rove-hotels', 'Rove Hotels', 'Rove Hotels', '2023–2024', id, 'Multi-property hospitality campaigns with a consistent, energetic brand voice.', 'Senior graphic design contribution across social, campaign and presentation work.', 'Adapted seasonal and property-specific messages into cohesive content families.', '["Social content", "Seasonal promotions", "Multi-property campaigns", "Presentations"]'::jsonb, 8, false, 'draft' from public.categories where slug = 'hospitality'
union all select 'caesars-palace-dubai', 'Caesars Palace Dubai', 'Caesars Palace Dubai', '2023', id, 'Hospitality collateral and seasonal campaign work across print, digital and presentation formats.', 'Selected design and production contribution.', 'Extended approved key visuals into clear, premium communication across guest touchpoints.', '["Campaign key visuals", "Digital flyers", "Presentations", "Seasonal collateral"]'::jsonb, 9, false, 'draft' from public.categories where slug = 'hospitality'
union all select 'marriott', 'Marriott', 'Marriott', '2023', id, 'Key-visual and messaging development for hospitality campaign communications.', 'Selected campaign design and adaptation work.', 'Contributed to visual and messaging development, then produced consistent social and print assets.', '["Key visual", "Messaging development", "Social campaign assets", "Print advertising"]'::jsonb, 10, false, 'draft' from public.categories where slug = 'hospitality';

insert into public.site_content (singleton, draft_content) values (true, '{}'::jsonb);
insert into public.theme_settings (singleton, draft_theme) values (true, '{}'::jsonb);
insert into public.published_site (singleton, revision, snapshot, published_at)
values (true, 0, '{"schemaVersion":1,"revision":0,"publishedAt":null,"theme":{},"sections":{},"projects":[],"categories":[],"media":[]}'::jsonb, now());
